# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GradeSubmissions(object):
    def setupUi(self, GradeSubmissions):
        GradeSubmissions.setObjectName("GradeSubmissions")
        GradeSubmissions.resize(291, 416)
        self.centralwidget = QtWidgets.QWidget(parent=GradeSubmissions)
        self.centralwidget.setObjectName("centralwidget")
        self.Name_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Name_lineEdit.setGeometry(QtCore.QRect(120, 10, 113, 20))
        self.Name_lineEdit.setObjectName("Name_lineEdit")
        self.StudentName_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.StudentName_label.setGeometry(QtCore.QRect(20, 10, 91, 16))
        self.StudentName_label.setObjectName("StudentName_label")
        self.Score1_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Score1_label.setGeometry(QtCore.QRect(50, 100, 51, 20))
        self.Score1_label.setMaximumSize(QtCore.QSize(666666, 16777215))
        self.Score1_label.setObjectName("Score1_label")
        self.Score1_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Score1_lineEdit.setGeometry(QtCore.QRect(120, 100, 113, 20))
        self.Score1_lineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.Score1_lineEdit.setObjectName("Score1_lineEdit")
        self.Score2_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Score2_lineEdit.setGeometry(QtCore.QRect(120, 130, 113, 21))
        self.Score2_lineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.Score2_lineEdit.setObjectName("Score2_lineEdit")
        self.Score3_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Score3_lineEdit.setGeometry(QtCore.QRect(120, 160, 113, 20))
        self.Score3_lineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.Score3_lineEdit.setObjectName("Score3_lineEdit")
        self.Score2_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Score2_label.setGeometry(QtCore.QRect(50, 130, 47, 13))
        self.Score2_label.setObjectName("Score2_label")
        self.Score3_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Score3_label.setGeometry(QtCore.QRect(50, 160, 47, 13))
        self.Score3_label.setObjectName("Score3_label")
        self.AvgScore_radioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.AvgScore_radioButton.setGeometry(QtCore.QRect(120, 210, 121, 17))
        self.AvgScore_radioButton.setObjectName("AvgScore_radioButton")
        self.HighScore_radioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.HighScore_radioButton.setGeometry(QtCore.QRect(120, 230, 111, 17))
        self.HighScore_radioButton.setObjectName("HighScore_radioButton")
        self.Submit_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Submit_pushButton.setGeometry(QtCore.QRect(130, 260, 75, 23))
        self.Submit_pushButton.setObjectName("Submit_pushButton")
        self.Assignment_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Assignment_label.setGeometry(QtCore.QRect(40, 40, 71, 16))
        self.Assignment_label.setObjectName("Assignment_label")
        self.Assignment_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Assignment_lineEdit.setGeometry(QtCore.QRect(120, 40, 113, 20))
        self.Assignment_lineEdit.setObjectName("Assignment_lineEdit")
        self.NumOfScores_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.NumOfScores_lineEdit.setGeometry(QtCore.QRect(120, 70, 113, 20))
        self.NumOfScores_lineEdit.setObjectName("NumOfScores_lineEdit")
        self.NumOfScore_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.NumOfScore_label.setGeometry(QtCore.QRect(40, 70, 71, 20))
        self.NumOfScore_label.setObjectName("NumOfScore_label")
        self.error_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.error_label.setGeometry(QtCore.QRect(50, 330, 211, 41))
        self.error_label.setObjectName("error_label")
        GradeSubmissions.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=GradeSubmissions)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 291, 21))
        self.menubar.setObjectName("menubar")
        GradeSubmissions.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=GradeSubmissions)
        self.statusbar.setObjectName("statusbar")
        GradeSubmissions.setStatusBar(self.statusbar)

        self.retranslateUi(GradeSubmissions)
        QtCore.QMetaObject.connectSlotsByName(GradeSubmissions)

    def retranslateUi(self, GradeSubmissions):
        _translate = QtCore.QCoreApplication.translate
        GradeSubmissions.setWindowTitle(_translate("GradeSubmissions", "Grade Submissons"))
        self.StudentName_label.setText(_translate("GradeSubmissions", "Student\'s Name:"))
        self.Score1_label.setText(_translate("GradeSubmissions", "Score 1:"))
        self.Score2_label.setText(_translate("GradeSubmissions", "Score 2:"))
        self.Score3_label.setText(_translate("GradeSubmissions", "Score 3:"))
        self.AvgScore_radioButton.setText(_translate("GradeSubmissions", "Average Score"))
        self.HighScore_radioButton.setText(_translate("GradeSubmissions", "Highest Score"))
        self.Submit_pushButton.setText(_translate("GradeSubmissions", "SUBMIT"))
        self.Assignment_label.setText(_translate("GradeSubmissions", "Assignment:"))
        self.NumOfScore_label.setText(_translate("GradeSubmissions", "# of scores: "))
        self.error_label.setText(_translate("GradeSubmissions", " "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GradeSubmissions = QtWidgets.QMainWindow()
    ui = Ui_GradeSubmissions()
    ui.setupUi(GradeSubmissions)
    GradeSubmissions.show()
    sys.exit(app.exec())
